<a href="https://colab.research.google.com/github/aycakrk/DI725_Ayca/blob/main/Final_Project/phase2_post.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!unzip "/content/drive/MyDrive/RISCM.zip" -d "/content"

Streaming output truncated to the last 5000 lines.
  inflating: /content/resized/RSICD_4364.jpg
  inflating: /content/resized/NWPU_18440.jpg
  inflating: /content/resized/NWPU_129.jpg
  inflating: /content/resized/NWPU_19322.jpg
  inflating: /content/resized/RSICD_3101.jpg
  inflating: /content/resized/UCM_2077.jpg
  inflating: /content/resized/NWPU_10992.jpg
  inflating: /content/resized/NWPU_10941.jpg
  inflating: /content/resized/NWPU_19048.jpg
  inflating: /content/resized/UCM_1535.jpg
  inflating: /content/resized/NWPU_22896.jpg
  inflating: /content/resized/NWPU_15332.jpg
  inflating: /content/resized/RSICD_7475.jpg
  inflating: /content/resized/NWPU_24431.jpg
  inflating: /content/resized/NWPU_25180.jpg
  inflating: /content/resized/RSICD_1536.jpg
  inflating: /content/resized/NWPU_18103.jpg
  inflating: /content/resized/NWPU_906.jpg
  inflating: /content/resized/NWPU_11526.jpg
  inflating: /content/resized/NWPU_22481.jpg
  inflating: /content/resized/NWPU_29001.jpg
  inflating: /content/resized/NWPU_18207.jpg
  inflating: /content/resized/NWPU_26448.jpg
  inflating: /content/resized/NWPU_7193.jpg
  inflating: /content/resized/UCM_288.jpg
  inflating: /content/resized/RSICD_10430.jpg
  inflating: /content/resized/NWPU_31285.jpg
  inflating: /content/resized/NWPU_21951.jpg
  inflating: /content/resized/RSICD_5686.jpg
  inflating: /content/resized/NWPU_1298.jpg
  inflating: /content/resized/RSICD_9561.jpg
  inflating: /content/resized/NWPU_4868.jpg
  inflating: /content/resized/NWPU_10956.jpg
  inflating: /content/resized/RSICD_6272.jpg
  inflating: /content/resized/RSICD_9942.jpg
  inflating: /content/resized/NWPU_17140.jpg
  inflating: /content/resized/NWPU_14786.jpg
  inflating: /content/resized/NWPU_28237.jpg
  inflating: /content/resized/NWPU_15480.jpg
  inflating: /content/resized/NWPU_27494.jpg
  inflating: /content/resized/NWPU_6966.jpg
  inflating: /content/resized/NWPU_18890.jpg
  inflating: /content/resized/NWPU_4792.jpg
  inflating: /content/resized/RSICD_417.jpg
  inflating: /content/resized/RSICD_9872.jpg
  inflating: /content/resized/RSICD_9578.jpg
  inflating: /content/resized/RSICD_9516.jpg
  inflating: /content/resized/RSICD_9913.jpg
  inflating: /content/resized/NWPU_8339.jpg
  inflating: /content/resized/NWPU_21620.jpg
  inflating: /content/resized/NWPU_2236.jpg
  inflating: /content/resized/NWPU_17696.jpg
  inflating: /content/resized/NWPU_30389.jpg
  inflating: /content/resized/NWPU_5276.jpg
  inflating: /content/resized/NWPU_6829.jpg
  inflating: /content/resized/NWPU_25384.jpg
  inflating: /content/resized/RSICD_9934.jpg
  inflating: /content/resized/RSICD_5577.jpg
  inflating: /content/resized/NWPU_30476.jpg
  inflating: /content/resized/RSICD_5722.jpg
  inflating: /content/resized/NWPU_4786.jpg
  inflating: /content/resized/NWPU_8508.jpg
  inflating: /content/resized/RSICD_10011.jpg
  inflating: /content/resized/NWPU_5773.jpg
  inflating: /content/resized/NWPU_27002.jpg
  inflating: /content/resized/RSICD_4459.jpg
  inflating: /content/resized/RSICD_9210.jpg
  inflating: /content/resized/RSICD_10801.jpg
  inflating: /content/resized/RSICD_4150.jpg
  inflating: /content/resized/RSICD_7247.jpg
  inflating: /content/resized/RSICD_6077.jpg
  inflating: /content/resized/UCM_307.jpg
  inflating: /content/resized/NWPU_29550.jpg
  inflating: /content/resized/RSICD_3063.jpg
  inflating: /content/resized/RSICD_611.jpg
  inflating: /content/resized/NWPU_19435.jpg
  inflating: /content/resized/UCM_1620.jpg
  inflating: /content/resized/RSICD_1302.jpg
  inflating: /content/resized/NWPU_21231.jpg
  inflating: /content/resized/RSICD_6095.jpg
  inflating: /content/resized/NWPU_16018.jpg
  inflating: /content/resized/NWPU_23697.jpg
  inflating: /content/resized/NWPU_14930.jpg
  inflating: /content/resized/RSICD_3926.jpg
  inflating: /content/resized/NWPU_16453.jpg
  inflating: /content/resized/RSICD_665.jpg
  inflating: /content/resized/RSICD_3912.jpg
  inflating: /content/resized/NWPU_29067.jpg
  inflating: /content/resized/NWPU_26863.jpg
  inflating: /content/resized/UCM_1061.jpg
  inflating: /content/resized/NWPU_19156.jpg
  inflating: /content/resized/NWPU_15935.jpg
  inflating: /content/resized/NWPU_3294.jpg
  inflating: /content/resized/NWPU_2029.jpg
  inflating: /content/resized/NWPU_30335.jpg
  inflating: /content/resized/NWPU_27088.jpg
  inflating: /content/resized/NWPU_1403.jpg
  inflating: /content/resized/NWPU_13506.jpg
  inflating: /content/resized/NWPU_3708.jpg
  inflating: /content/resized/RSICD_9014.jpg
  inflating: /content/resized/NWPU_30369.jpg
  inflating: /content/resized/NWPU_20978.jpg
  inflating: /content/resized/NWPU_18722.jpg
  inflating: /content/resized/RSICD_2219.jpg
  inflating: /content/resized/NWPU_18465.jpg
  inflating: /content/resized/RSICD_7240.jpg
  inflating: /content/resized/NWPU_192.jpg
  inflating: /content/resized/NWPU_5896.jpg
  inflating: /content/resized/NWPU_11270.jpg
  inflating: /content/resized/RSICD_6984.jpg
  inflating: /content/resized/NWPU_12745.jpg
  inflating: /content/resized/NWPU_31425.jpg
  inflating: /content/resized/NWPU_20243.jpg
  inflating: /content/resized/RSICD_6321.jpg
  inflating: /content/resized/RSICD_2379.jpg
  inflating: /content/resized/RSICD_6541.jpg
  inflating: /content/resized/NWPU_3025.jpg
  inflating: /content/resized/RSICD_7162.jpg
  inflating: /content/resized/NWPU_24427.jpg
  inflating: /content/resized/NWPU_8769.jpg
  inflating: /content/resized/UCM_1907.jpg
  inflating: /content/resized/NWPU_4598.jpg
  inflating: /content/resized/NWPU_21982.jpg
  inflating: /content/resized/NWPU_15220.jpg
  inflating: /content/resized/RSICD_5094.jpg
  inflating: /content/resized/NWPU_18809.jpg
  inflating: /content/resized/NWPU_25165.jpg
  inflating: /content/resized/RSICD_974.jpg
  inflating: /content/resized/RSICD_8942.jpg
  inflating: /content/resized/NWPU_25736.jpg
  inflating: /content/resized/NWPU_15321.jpg
  inflating: /content/resized/NWPU_24833.jpg
  inflating: /content/resized/NWPU_21126.jpg
  inflating: /content/resized/NWPU_30705.jpg
  inflating: /content/resized/NWPU_16409.jpg
  inflating: /content/resized/NWPU_16495.jpg
  inflating: /content/resized/RSICD_8725.jpg
  inflating: /content/resized/NWPU_23186.jpg
  inflating: /content/resized/RSICD_8634.jpg
  inflating: /content/resized/RSICD_1272.jpg
  inflating: /content/resized/NWPU_26392.jpg
  inflating: /content/resized/RSICD_1847.jpg
  inflating: /content/resized/NWPU_16198.jpg
  inflating: /content/resized/RSICD_7204.jpg
  inflating: /content/resized/NWPU_30266.jpg
  inflating: /content/resized/NWPU_2845.jpg
  inflating: /content/resized/NWPU_8901.jpg
  inflating: /content/resized/UCM_396.jpg
  inflating: /content/resized/NWPU_782.jpg
  inflating: /content/resized/RSICD_3132.jpg
  inflating: /content/resized/NWPU_26524.jpg
  inflating: /content/resized/NWPU_15418.jpg
  inflating: /content/resized/RSICD_8837.jpg
  inflating: /content/resized/NWPU_4385.jpg
  inflating: /content/resized/NWPU_15358.jpg
  inflating: /content/resized/NWPU_29083.jpg
  inflating: /content/resized/NWPU_26821.jpg
  inflating: /content/resized/RSICD_2396.jpg
  inflating: /content/resized/NWPU_22366.jpg
  inflating: /content/resized/NWPU_24110.jpg
  inflating: /content/resized/NWPU_9347.jpg
  inflating: /content/resized/NWPU_7846.jpg
  inflating: /content/resized/NWPU_19934.jpg
  inflating: /content/resized/NWPU_16678.jpg
  inflating: /content/resized/NWPU_15723.jpg
  inflating: /content/resized/NWPU_11431.jpg
  inflating: /content/resized/NWPU_21692.jpg
  inflating: /content/resized/RSICD_5706.jpg
  inflating: /content/resized/NWPU_14660.jpg
  inflating: /content/resized/NWPU_28773.jpg
  inflating: /content/resized/RSICD_6921.jpg
  inflating: /content/resized/NWPU_12073.jpg
  inflating: /content/resized/RSICD_3753.jpg
  inflating: /content/resized/NWPU_20011.jpg
  inflating: /content/resized/UCM_173.jpg
  inflating: /content/resized/NWPU_3226.jpg
  inflating: /content/resized/UCM_825.jpg
  inflating: /content/resized/NWPU_18106.jpg
  inflating: /content/resized/NWPU_24248.jpg
  inflating: /content/resized/NWPU_3372.jpg
  inflating: /content/resized/NWPU_14054.jpg
  inflating: /content/resized/NWPU_26081.jpg
  inflating: /content/resized/NWPU_3740.jpg
  inflating: /content/resized/NWPU_23109.jpg
  inflating: /content/resized/NWPU_2608.jpg
  inflating: /content/resized/NWPU_20456.jpg
  inflating: /content/resized/RSICD_10007.jpg
  inflating: /content/resized/NWPU_8766.jpg
  inflating: /content/resized/NWPU_8238.jpg
  inflating: /content/resized/RSICD_8507.jpg
  inflating: /content/resized/NWPU_17861.jpg
  inflating: /content/resized/RSICD_10012.jpg
  inflating: /content/resized/NWPU_5036.jpg
  inflating: /content/resized/NWPU_7693.jpg
  inflating: /content/resized/NWPU_28452.jpg
  inflating: /content/resized/NWPU_20447.jpg
  inflating: /content/resized/NWPU_12543.jpg
  inflating: /content/resized/RSICD_10385.jpg
  inflating: /content/resized/NWPU_27076.jpg
  inflating: /content/resized/NWPU_12867.jpg
  inflating: /content/resized/NWPU_23311.jpg
  inflating: /content/resized/NWPU_20630.jpg
  inflating: /content/resized/NWPU_30613.jpg
  inflating: /content/resized/NWPU_17530.jpg
  inflating: /content/resized/NWPU_21799.jpg
  inflating: /content/resized/NWPU_6357.jpg
  inflating: /content/resized/NWPU_5789.jpg
  inflating: /content/resized/NWPU_36.jpg
  inflating: /content/resized/NWPU_20953.jpg
  inflating: /content/resized/NWPU_23974.jpg
  inflating: /content/resized/RSICD_3992.jpg
  inflating: /content/resized/NWPU_29895.jpg
  inflating: /content/resized/NWPU_11772.jpg
  inflating: /content/resized/NWPU_11395.jpg
  inflating: /content/resized/RSICD_10015.jpg
  inflating: /content/resized/NWPU_14952.jpg
  inflating: /content/resized/RSICD_1809.jpg
  inflating: /content/resized/RSICD_9645.jpg
  inflating: /content/resized/NWPU_6204.jpg
  inflating: /content/resized/NWPU_12957.jpg
  inflating: /content/resized/NWPU_14615.jpg
  inflating: /content/resized/NWPU_21869.jpg
  inflating: /content/resized/RSICD_1982.jpg
  inflating: /content/resized/UCM_356.jpg
  inflating: /content/resized/RSICD_327.jpg
  inflating: /content/resized/RSICD_7239.jpg
  inflating: /content/resized/NWPU_9456.jpg
  inflating: /content/resized/NWPU_29376.jpg
  inflating: /content/resized/RSICD_10858.jpg
  inflating: /content/resized/NWPU_9722.jpg
  inflating: /content/resized/RSICD_5544.jpg
  inflating: /content/resized/NWPU_4469.jpg
  inflating: /content/resized/NWPU_23728.jpg
  inflating: /content/resized/NWPU_28543.jpg
  inflating: /content/resized/NWPU_20976.jpg
  inflating: /content/resized/NWPU_20215.jpg
  inflating: /content/resized/NWPU_14101.jpg
  inflating: /content/resized/NWPU_705.jpg
  inflating: /content/resized/NWPU_22136.jpg
  inflating: /content/resized/RSICD_7256.jpg
  inflating: /content/resized/RSICD_9864.jpg
  inflating: /content/resized/NWPU_13140.jpg
  inflating: /content/resized/NWPU_19929.jpg
  inflating: /content/resized/NWPU_24681.jpg
  inflating: /content/resized/RSICD_8116.jpg
  inflating: /content/resized/NWPU_4120.jpg
  inflating: /content/resized/NWPU_5166.jpg
  inflating: /content/resized/NWPU_29839.jpg
  inflating: /content/resized/NWPU_27049.jpg
  inflating: /content/resized/NWPU_2789.jpg
  inflating: /content/resized/NWPU_10198.jpg
  inflating: /content/resized/RSICD_1606.jpg
  inflating: /content/resized/NWPU_29058.jpg
  inflating: /content/resized/NWPU_16727.jpg
  inflating: /content/resized/NWPU_12935.jpg
  inflating: /content/resized/NWPU_30706.jpg
  inflating: /content/resized/NWPU_27549.jpg
  inflating: /content/resized/RSICD_9632.jpg
  inflating: /content/resized/NWPU_27535.jpg
  inflating: /content/resized/NWPU_18761.jpg
  inflating: /content/resized/NWPU_24388.jpg
  inflating: /content/resized/NWPU_19506.jpg
  inflating: /content/resized/RSICD_10668.jpg
  inflating: /content/resized/NWPU_2106.jpg
  inflating: /content/resized/NWPU_8495.jpg
  inflating: /content/resized/NWPU_24380.jpg
  inflating: /content/resized/RSICD_7269.jpg
  inflating: /content/resized/NWPU_3266.jpg
  inflating: /content/resized/UCM_897.jpg
  inflating: /content/resized/RSICD_9811.jpg
  inflating: /content/resized/NWPU_12049.jpg
  inflating: /content/resized/NWPU_2513.jpg
  inflating: /content/resized/RSICD_10114.jpg
  inflating: /content/resized/NWPU_12578.jpg
  inflating: /content/resized/NWPU_22832.jpg
  inflating: /content/resized/UCM_1481.jpg
  inflating: /content/resized/NWPU_1794.jpg
  inflating: /content/resized/NWPU_30264.jpg
  inflating: /content/resized/NWPU_21769.jpg
  inflating: /content/resized/NWPU_12913.jpg
  inflating: /content/resized/RSICD_1222.jpg
  inflating: /content/resized/NWPU_20465.jpg
  inflating: /content/resized/NWPU_8081.jpg
  inflating: /content/resized/NWPU_13295.jpg
  inflating: /content/resized/NWPU_2074.jpg
  inflating: /content/resized/NWPU_19571.jpg
  inflating: /content/resized/RSICD_8209.jpg
  inflating: /content/resized/NWPU_6962.jpg
  inflating: /content/resized/RSICD_7128.jpg
  inflating: /content/resized/NWPU_1331.jpg
  inflating: /content/resized/RSICD_7437.jpg
  inflating: /content/resized/RSICD_3744.jpg
  inflating: /content/resized/NWPU_27087.jpg
  inflating: /content/resized/UCM_248.jpg
  inflating: /content/resized/RSICD_3779.jpg
  inflating: /content/resized/NWPU_17207.jpg
  inflating: /content/resized/NWPU_12257.jpg
  inflating: /content/resized/NWPU_12415.jpg
  inflating: /content/resized/NWPU_23130.jpg
  inflating: /content/resized/NWPU_23959.jpg
  inflating: /content/resized/NWPU_11040.jpg
  inflating: /content/resized/RSICD_2010.jpg
  inflating: /content/resized/RSICD_3742.jpg
  inflating: /content/resized/NWPU_21178.jpg
  inflating: /content/resized/RSICD_2341.jpg
  inflating: /content/resized/RSICD_5064.jpg
  inflating: /content/resized/NWPU_16449.jpg
  inflating: /content/resized/UCM_1519.jpg
  inflating: /content/resized/NWPU_31336.jpg
  inflating: /content/resized/NWPU_5311.jpg
  inflating: /content/resized/NWPU_27214.jpg
  inflating: /content/resized/NWPU_12448.jpg
  inflating: /content/resized/RSICD_2479.jpg
  inflating: /content/resized/RSICD_2881.jpg
  inflating: /content/resized/NWPU_23168.jpg
  inflating: /content/resized/UCM_87.jpg
  inflating: /content/resized/RSICD_8758.jpg
  inflating: /content/resized/UCM_1429.jpg
  inflating: /content/resized/RSICD_7984.jpg
  inflating: /content/resized/NWPU_23185.jpg
  inflating: /content/resized/NWPU_19604.jpg
  inflating: /content/resized/NWPU_1602.jpg
  inflating: /content/resized/RSICD_691.jpg
  inflating: /content/resized/NWPU_28340.jpg
  inflating: /content/resized/NWPU_9760.jpg
  inflating: /content/resized/UCM_1225.jpg
  inflating: /content/resized/NWPU_15684.jpg
  inflating: /content/resized/NWPU_1841.jpg
  inflating: /content/resized/NWPU_1716.jpg
  inflating: /content/resized/NWPU_8666.jpg
  inflating: /content/resized/UCM_36.jpg
  inflating: /content/resized/NWPU_31404.jpg
  inflating: /content/resized/NWPU_5780.jpg
  inflating: /content/resized/NWPU_3102.jpg
  inflating: /content/resized/NWPU_29529.jpg
  inflating: /content/resized/NWPU_28117.jpg
  inflating: /content/resized/NWPU_27472.jpg
  inflating: /content/resized/NWPU_21880.jpg
  inflating: /content/resized/NWPU_1383.jpg
  inflating: /content/resized/NWPU_15960.jpg
  inflating: /content/resized/UCM_1159.jpg
  inflating: /content/resized/NWPU_27197.jpg
  inflating: /content/resized/NWPU_21168.jpg
  inflating: /content/resized/NWPU_15992.jpg
  inflating: /content/resized/NWPU_5569.jpg
  inflating: /content/resized/UCM_819.jpg
  inflating: /content/resized/NWPU_15344.jpg
  inflating: /content/resized/RSICD_492.jpg
  inflating: /content/resized/NWPU_26890.jpg
  inflating: /content/resized/NWPU_8559.jpg
  inflating: /content/resized/NWPU_24596.jpg
  inflating: /content/resized/NWPU_9786.jpg
  inflating: /content/resized/NWPU_1482.jpg
  inflating: /content/resized/NWPU_19381.jpg
  inflating: /content/resized/NWPU_30134.jpg
  inflating: /content/resized/NWPU_20426.jpg
  inflating: /content/resized/RSICD_3026.jpg
  inflating: /content/resized/NWPU_29088.jpg
  inflating: /content/resized/NWPU_30665.jpg
  inflating: /content/resized/NWPU_8627.jpg
  inflating: /content/resized/NWPU_25773.jpg
  inflating: /content/resized/NWPU_8528.jpg
  inflating: /content/resized/NWPU_26541.jpg
  inflating: /content/resized/NWPU_30583.jpg
  inflating: /content/resized/NWPU_16476.jpg
  inflating: /content/resized/NWPU_19211.jpg
  inflating: /content/resized/NWPU_9304.jpg
  inflating: /content/resized/RSICD_8611.jpg
  inflating: /content/resized/NWPU_24714.jpg
  inflating: /content/resized/UCM_2001.jpg
  inflating: /content/resized/RSICD_1027.jpg
  inflating: /content/resized/NWPU_2382.jpg
  inflating: /content/resized/NWPU_25383.jpg
  inflating: /content/resized/NWPU_21059.jpg
  inflating: /content/resized/NWPU_11412.jpg
  inflating: /content/resized/UCM_198.jpg
  inflating: /content/resized/NWPU_15629.jpg
  inflating: /content/resized/NWPU_24173.jpg
  inflating: /content/resized/NWPU_25358.jpg
  inflating: /content/resized/RSICD_8759.jpg
  inflating: /content/resized/RSICD_8043.jpg
  inflating: /content/resized/RSICD_9175.jpg
  inflating: /content/resized/NWPU_14381.jpg
  inflating: /content/resized/NWPU_3911.jpg
  inflating: /content/resized/RSICD_3627.jpg
  inflating: /content/resized/RSICD_9572.jpg
  inflating: /content/resized/UCM_1373.jpg
  inflating: /content/resized/RSICD_10842.jpg
  inflating: /content/resized/NWPU_27538.jpg
  inflating: /content/resized/NWPU_24762.jpg
  inflating: /content/resized/RSICD_10625.jpg
  inflating: /content/resized/NWPU_19814.jpg
  inflating: /content/resized/NWPU_6226.jpg
  inflating: /content/resized/NWPU_17757.jpg
  inflating: /content/resized/NWPU_12828.jpg
  inflating: /content/resized/RSICD_2784.jpg
  inflating: /content/resized/NWPU_14502.jpg
  inflating: /content/resized/NWPU_13706.jpg
  inflating: /content/resized/NWPU_25988.jpg
  inflating: /content/resized/RSICD_8570.jpg
  inflating: /content/resized/NWPU_30280.jpg
  inflating: /content/resized/UCM_497.jpg
  inflating: /content/resized/NWPU_10579.jpg
  inflating: /content/resized/NWPU_11575.jpg
  inflating: /content/resized/UCM_774.jpg
  inflating: /content/resized/NWPU_16383.jpg
  inflating: /content/resized/RSICD_1965.jpg
  inflating: /content/resized/NWPU_20383.jpg
  inflating: /content/resized/NWPU_17818.jpg
  inflating: /content/resized/NWPU_27126.jpg
  inflating: /content/resized/NWPU_7842.jpg
  inflating: /content/resized/NWPU_6765.jpg
  inflating: /content/resized/RSICD_9677.jpg
  inflating: /content/resized/NWPU_18959.jpg
  inflating: /content/resized/NWPU_11547.jpg
  inflating: /content/resized/NWPU_24496.jpg
  inflating: /content/resized/NWPU_26268.jpg
  inflating: /content/resized/NWPU_11216.jpg
  inflating: /content/resized/NWPU_2690.jpg
  inflating: /content/resized/NWPU_21812.jpg
  inflating: /content/resized/NWPU_21742.jpg
  inflating: /content/resized/RSICD_2626.jpg
  inflating: /content/resized/NWPU_5011.jpg
  inflating: /content/resized/RSICD_2221.jpg
  inflating: /content/resized/NWPU_28403.jpg
  inflating: /content/resized/UCM_393.jpg
  inflating: /content/resized/NWPU_6113.jpg
  inflating: /content/resized/RSICD_10125.jpg
  inflating: /content/resized/NWPU_3556.jpg
  inflating: /content/resized/NWPU_10320.jpg
  inflating: /content/resized/NWPU_29869.jpg
  inflating: /content/resized/RSICD_2154.jpg
  inflating: /content/resized/NWPU_18130.jpg
  inflating: /content/resized/NWPU_16096.jpg
  inflating: /content/resized/NWPU_5778.jpg
  inflating: /content/resized/RSICD_6985.jpg
  inflating: /content/resized/NWPU_22203.jpg
  inflating: /content/resized/NWPU_20453.jpg
  inflating: /content/resized/NWPU_8613.jpg
  inflating: /content/resized/RSICD_4897.jpg
  inflating: /content/resized/NWPU_19416.jpg
  inflating: /content/resized/NWPU_2688.jpg
  inflating: /content/resized/NWPU_30399.jpg
  inflating: /content/resized/NWPU_18993.jpg
  inflating: /content/resized/NWPU_21048.jpg
  inflating: /content/resized/NWPU_17825.jpg

In [3]:
# Örnek: captions.csv'yi oku
import pandas as pd
df = pd.read_csv('captions.csv')
df.head()

,source,split,image,caption_1,caption_2,caption_3,caption_4,caption_5
0,NWPU,test,NWPU_31430.jpg,A gray plane on the runway and the lawn beside .,A grey plane is on the runway by the lawn .,There is an airplane on the runway with a larg...,A plane is parked on the runway next to the gr...,There is a plane on the runway beside the grass .
1,NWPU,test,NWPU_31431.jpg,Three small planes parked in a line on the air...,"There are four aircraft on the open ground, Th...",There are many planes of different sizes in a ...,Four planes are parked on the runway .,Four planes of different sizes were on the mar...
2,NWPU,test,NWPU_31432.jpg,A plane parked in a line on the airport with s...,A white plane was parked on the instruction li...,An airplane parked in an open area with many c...,A plane is parked on the open space .,There is 1 plane on the ground marked .
3,NWPU,test,NWPU_31433.jpg,A small plane and a big plane parked next to b...,A white plane and a gray plane parked at the b...,Two planes of different sizes are neatly parke...,A large plane and a small plane are parked nea...,Two planes are on the marked ground .
4,NWPU,test,NWPU_31434.jpg,Two planes parked next to boarding bridges .,Two aircraft were parked at the departure gates .,Two planes of different sizes are neatly parke...,Two planes are parked next to the terminal .,Two planes are on the marked ground .

In [4]:
!pip install huggingface_hub
!pip install evaluate transformers tqdm wandb
!pip install rouge_score
!pip install pycocoevalcap

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.11/dist-packages (0.31.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (2025.3.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface_hub) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface_hub) (2025.4.26)
Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.51.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)
Requirement already satisfied: wandb in /usr/local/lib/python3.11/dist-packages (0.19.11)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.14.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.15)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.2)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.31.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: click!=8.0.0,>=7.1 in /usr/local/lib/python3.11/dist-packages (from wandb) (8.2.0)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (3.1.44)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.11/dist-packages (from wandb) (4.3.8)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.19.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (5.29.4)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (5.9.5)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.11/dist-packages (from wandb) (2.11.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from wandb) (2.28.0)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.11/dist-packages (from wandb) (1.3.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from wandb) (75.2.0)
Requirement already satisfied: typing-extensions<5,>=4.4 in /usr/local/lib/python3.11/dist-packages (from wandb) (4.13.2)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.15)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from docker-pycreds>=0.4.0->wandb) (1.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.11/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3->wandb) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3->wandb) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.20.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.2)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 2.6 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.3
Collecting rouge_score
  Downloading rouge_score-0.1.2.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from rouge_score) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from rouge_score) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from rouge_score) (2.0.2)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.11/dist-packages (from rouge_score) (1.17.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (8.2.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (1.5.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk->rouge_score) (4.67.1)
Building wheels for collected packages: rouge_score
  Building wheel for rouge_score (setup.py) ... done
  Created wheel for rouge_score: filename=rouge_score-0.1.2-py3-none-any.whl size=24934 sha256=503fe7aaf0d385a1fdab6696d46a641e15924c0a96472cc4bd206b93327e5b43
  Stored in directory: /root/.cache/pip/wheels/1e/19/43/8a442dc83660ca25e163e1bd1f89919284ab0d0c1475475148
Successfully built rouge_score
Installing collected packages: rouge_score
Successfully installed rouge_score-0.1.2
Collecting pycocoevalcap
  Downloading pycocoevalcap-1.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: pycocotools>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from pycocoevalcap) (2.0.8)
Requirement already satisfied: matplotlib>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from pycocotools>=2.0.2->pycocoevalcap) (3.10.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from pycocotools>=2.0.2->pycocoevalcap) (2.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap) (4.58.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=2.1.0->pycocotools>=2.0.2->pycocoevalcap) (1.17.0)
Downloading pycocoevalcap-1.2-py3-none-any.whl (104.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.3/104.3 MB 24.3 MB/s eta 0:00:00
Installing collected packages: pycocoevalcap
Successfully installed pycocoevalcap-1.2

In [5]:
from huggingface_hub import notebook_login
notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [6]:
import pandas as pd
import os
from sklearn.model_selection import train_test_split

train_df = df[df["split"] == "train"].copy()
val_df   = df[df["split"] == "val"].copy()
test_df  = df[df["split"] == "test"].copy()

# length evaluation
n_train = len(train_df)
n_val   = len(val_df)
n_test  = len(test_df)
total   = n_train + n_val + n_test

print(f"Train: {n_train} ({n_train/total:.2%})")
print(f"Test:  {n_test}  ({n_test/total:.2%})")
print(f"Val:   {n_val}   ({n_val/total:.2%})")

img_dir = '/content/resized'
all_images = set(os.listdir(img_dir))
df_images  = set(df['image'].unique())

missing = sorted(list(df_images - all_images))
if missing:
    print(f"Eksik {len(missing)} dosya var. Örnekler:", missing[:10])
else:
    print("Tüm caption’daki image isimleri klasörde bulundu.")

Train: 35614 (79.99%)
Test:  4454  (10.00%)
Val:   4453   (10.00%)
Tüm caption’daki image isimleri klasörde bulundu.

In [ ]:
from transformers import Seq2SeqTrainingArguments

args = Seq2SeqTrainingArguments(output_dir="dummy_dir")

gen_params = [
    "generation_num_beams",
    "generation_no_repeat_ngram_size",
    "generation_repetition_penalty",
    "generation_early_stopping",
    "generation_do_sample",
    "generation_top_p",
    "generation_temperature"
]

for param in gen_params:
    print(f"{param}: Exists = {hasattr(args, param)}, Default = {getattr(args, param, None)}")

generation_num_beams: Exists = True, Default = None
generation_no_repeat_ngram_size: Exists = False, Default = None
generation_repetition_penalty: Exists = False, Default = None
generation_early_stopping: Exists = False, Default = None
generation_do_sample: Exists = False, Default = None
generation_top_p: Exists = False, Default = None
generation_temperature: Exists = False, Default = None

sorun diğer beamleri beklemesi mi?

In [ ]:
import os
import random
from PIL import Image
import wandb

import torch
from torch.utils.data import Dataset

from transformers import (
    AutoProcessor,
    AutoModelForImageTextToText,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    default_data_collator,
    BitsAndBytesConfig,
    GenerationConfig
)
from peft import LoraConfig, get_peft_model, TaskType
import evaluate
from pycocoevalcap.cider.cider import Cider
import pandas as pd

# -------------------------------------------
# 0) WANDB oturumunu başlat (opsiyonel)
# -------------------------------------------
wandb.init(project="DI725_FinalProject", name="lora_r8_eos_gen")

# -------------------------------------------
# 1) Processor & Base Model (8-bit + CPU offload)
# -------------------------------------------
model_name = "google/paligemma-3b-pt-224"
processor  = AutoProcessor.from_pretrained(model_name, use_auth_token=True)
tokenizer  = processor.tokenizer #eklendi

base_model = AutoModelForImageTextToText.from_pretrained(
    model_name,
    device_map="auto",
    use_auth_token=True
)

# Bellek rahatlasın diye gradient checkpointing
base_model.gradient_checkpointing_enable()
base_model.to("cuda")
base_model.eval()

# -------------------------------------------
# 2) Dinamik Caption Dataset
# -------------------------------------------
class RiscDynamicCaptionDataset(Dataset):
    def __init__(self, df, img_dir, processor, max_len=64):
        self.df      = df.reset_index(drop=True)
        self.img_dir = img_dir
        self.proc    = processor
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(os.path.join(self.img_dir, row["image"])).convert("RGB")
        caps = [row[f"caption_{i}"] for i in range(1,6)]
        cap  = "<image> " + random.choice(caps) + tokenizer.eos_token  # EOS token eklendi

        enc = self.proc(
            images=img,
            text=cap,
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors="pt"
        )
        pixel_values   = enc.pixel_values.squeeze(0)
        input_ids      = enc.input_ids.squeeze(0)
        attention_mask = enc.attention_mask.squeeze(0)

        return {
            "pixel_values":   pixel_values,
            "input_ids":      input_ids,
            "attention_mask": attention_mask,
            "labels":         input_ids.clone()
        }

# -------------------------------------------
# 3) Train / Val Dataset’leri yükle
# -------------------------------------------
img_dir  = "/content/resized"
train_ds = RiscDynamicCaptionDataset(train_df, img_dir, processor)
val_ds   = RiscDynamicCaptionDataset(val_df,   img_dir, processor)

# -------------------------------------------
# 4) LoRA Konfigürasyonu & PEFT Model
# -------------------------------------------
lora_cfg = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj"]
)
model_lora = get_peft_model(base_model, lora_cfg)
model_lora.print_trainable_parameters()

# -------------------------------------------
# 5) TrainingArguments & Trainer
# -------------------------------------------

training_args = Seq2SeqTrainingArguments(
    output_dir="lora_r8",
    per_device_train_batch_size=3,
    gradient_accumulation_steps=4,
    learning_rate=5e-5,
    num_train_epochs=1,
    logging_steps=5,
    eval_strategy="epoch",
    # her `logging_steps` adımında log’la
    logging_strategy="steps",
    predict_with_generate=True,
    fp16=True,
    push_to_hub=False,
    report_to="wandb",
    generation_num_beams=1

)


trainer = Seq2SeqTrainer(
    model=model_lora,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=default_data_collator,
    tokenizer=processor
)

# -------------------------------------------
# 6) Eğitim & Değerlendirme
# -------------------------------------------
trainer.train()
lora_metrics = trainer.evaluate()
print("LoRA metrics:", lora_metrics)

# -------------------------------------------
# 7) CIDEr’i ayrı hesaplamak istersen
# -------------------------------------------
preds = trainer.predict(val_ds).predictions
decoded_preds = processor.tokenizer.batch_decode(preds, skip_special_tokens=True)
references = val_df[[f"caption_{i}" for i in range(1,6)]].values.tolist()

refs_dict  = {i: references[i] for i in range(len(references))}
preds_dict = {i: [decoded_preds[i]]     for i in range(len(decoded_preds))}
cider_scorer = Cider()
cider_score, _ = cider_scorer.compute_score(refs_dict, preds_dict)
print("LoRA CIDEr:", cider_score)


# Changed: Pass keyword arguments 'references' and 'predictions' to compute()
bleu_res   = evaluate.load("bleu"  ).compute(references=references, predictions=decoded_preds)["bleu"]
meteor_res = evaluate.load("meteor").compute(references=references, predictions=decoded_preds)["meteor"]
rouge_res  = evaluate.load("rouge" ).compute(references=references, predictions=decoded_preds)["rougeL"]


print(f"BLEU:    {bleu_res:.4f}")
print(f"METEOR:  {meteor_res:.4f}")
print(f"ROUGE-L: {rouge_res:.4f}")
print(f"CIDEr:   {cider_score:.4f}")

wandb.log({
    "bleu":   bleu_res,
    "meteor": meteor_res,
    "rougeL": rouge_res,
    "cider":  cider_score
})


# -------------------------------------------
# 8) Sonuçları CSV’e ve wandbye yaz
# -------------------------------------------
rows = []
for i, img_name in enumerate(val_ds.df["image"].tolist()):
    row = {"image": img_name, "pred": decoded_preds[i]}
    for j, r in enumerate(references[i], start=1):
        row[f"ref_{j}"] = r
    rows.append(row)

pd.DataFrame(rows).to_csv("lora_r8_eos_gen_val_results.csv", index=False)
print("Saved CSV → lora_r8_val_eos_gen_results.csv")

n_samples = 5
# Veri seti uzunluğu
N = len(decoded_preds)
# Rastgele indeksler
sample_idxs = random.sample(range(N), n_samples)

# Bir tablo oluştur
table = wandb.Table(columns=["image", "prediction", "references"])

for i in sample_idxs:
    img_name   = val_ds.df["image"].iloc[i]
    pred       = decoded_preds[i]
    refs       = references[i]  # list of ground-truth’ler
    # referansları tek stringde birleştir
    refs_str   = " || ".join(refs)
    table.add_data(img_name, pred, refs_str)

# Tabloyu logla
wandb.log({"examples": table})

wandb: Currently logged in as: ayca-krk (ayca-krk-metu-middle-east-technical-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.11/dist-packages/transformers/models/auto/processing_auto.py:243: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
/usr/local/lib/python3.11/dist-packages/transformers/models/auto/auto_factory.py:476: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

<ipython-input-4-401bb4857255>:127: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(
No label_names provided for model class `PeftModelForSeq2SeqLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainable params: 1,916,928 || all params: 2,925,383,408 || trainable%: 0.0655

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
`labels` contains `pad_token_id` which will be masked with `config.ignore_index`. You have to mask out `pad_token_id` when preparing `labels`, this behavior will be removed in v.4.46.
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(

LoRA metrics: {'eval_loss': 12.382898330688477, 'eval_runtime': 97.3755, 'eval_samples_per_second': 45.73, 'eval_steps_per_second': 5.72, 'epoch': 1.0}
LoRA CIDEr: 0.24571306323919537

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

Downloading builder script:   0%|          | 0.00/7.02k [00:00<?, ?B/s]

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

Downloading builder script:   0%|          | 0.00/6.27k [00:00<?, ?B/s]

BLEU:    0.3825
METEOR:  0.8664
ROUGE-L: 0.8629
CIDEr:   0.2457
Saved CSV → lora_r8_val_eos_gen_results.csv

beam_num=1 yaptım ki tekrarlama sorunu diğr beamleri bekleyene kadar kendince eos tokenı gelmiş olsa bile ekleme yapması mı anlamaktı. ancak 1 desek bile tekrar problemi devam etti.

lets try config again

In [ ]:
import os
import random
from PIL import Image
import wandb

import torch
from torch.utils.data import Dataset

from transformers import (
    AutoProcessor,
    AutoModelForImageTextToText,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    default_data_collator,
    BitsAndBytesConfig,
    GenerationConfig
)
from peft import LoraConfig, get_peft_model, TaskType
import evaluate
from pycocoevalcap.cider.cider import Cider
import pandas as pd

# -------------------------------------------
# 0) WANDB oturumunu başlat (opsiyonel)
# -------------------------------------------
wandb.init(project="DI725_FinalProject", name="lora_r8_eos_gen")

# -------------------------------------------
# 1) Processor & Base Model (8-bit + CPU offload)
# -------------------------------------------
model_name = "google/paligemma-3b-pt-224"
processor  = AutoProcessor.from_pretrained(model_name, use_auth_token=True)
tokenizer  = processor.tokenizer #eklendi

base_model = AutoModelForImageTextToText.from_pretrained(
    model_name,
    device_map="auto",
    use_auth_token=True
)

# Bellek rahatlasın diye gradient checkpointing
base_model.gradient_checkpointing_enable()
base_model.to("cuda")
base_model.eval()

# -------------------------------------------
# 2) Dinamik Caption Dataset
# -------------------------------------------
class RiscDynamicCaptionDataset(Dataset):
    def __init__(self, df, img_dir, processor, max_len=64):
        self.df      = df.reset_index(drop=True)
        self.img_dir = img_dir
        self.proc    = processor
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(os.path.join(self.img_dir, row["image"])).convert("RGB")
        caps = [row[f"caption_{i}"] for i in range(1,6)]
        cap  = "<image> " + random.choice(caps) + tokenizer.eos_token  # EOS token eklendi

        enc = self.proc(
            images=img,
            text=cap,
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors="pt"
        )
        pixel_values   = enc.pixel_values.squeeze(0)
        input_ids      = enc.input_ids.squeeze(0)
        attention_mask = enc.attention_mask.squeeze(0)

        return {
            "pixel_values":   pixel_values,
            "input_ids":      input_ids,
            "attention_mask": attention_mask,
            "labels":         input_ids.clone()
        }

# -------------------------------------------
# 3) Train / Val Dataset’leri yükle
# -------------------------------------------
img_dir  = "/content/resized"
train_ds = RiscDynamicCaptionDataset(train_df, img_dir, processor)
val_ds   = RiscDynamicCaptionDataset(val_df,   img_dir, processor)

# -------------------------------------------
# 4) LoRA Konfigürasyonu & PEFT Model
# -------------------------------------------
lora_cfg = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj"]
)
model_lora = get_peft_model(base_model, lora_cfg)
model_lora.print_trainable_parameters()

# -------------------------------------------
# 5) TrainingArguments & Trainer
# -------------------------------------------
gen_cfg = GenerationConfig(
    repetition_penalty=1.5,           # tekrarlanan token’lara 1.5× ceza
    eos_token_id=tokenizer.eos_token_id,
)

training_args = Seq2SeqTrainingArguments(
    output_dir="lora_r8",
    per_device_train_batch_size=3,
    gradient_accumulation_steps=4,
    learning_rate=5e-5,
    num_train_epochs=1,
    logging_steps=5,
    eval_strategy="epoch",
    # her `logging_steps` adımında log’la
    logging_strategy="steps",
    predict_with_generate=True,
    generation_config=gen_cfg,
    fp16=True,
    push_to_hub=False,
    report_to="wandb"

)


trainer = Seq2SeqTrainer(
    model=model_lora,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=default_data_collator,
    tokenizer=processor
)

# -------------------------------------------
# 6) Eğitim & Değerlendirme
# -------------------------------------------
trainer.train()
lora_metrics = trainer.evaluate()
print("LoRA metrics:", lora_metrics)

# -------------------------------------------
# 7) CIDEr’i ayrı hesaplamak istersen
# -------------------------------------------
preds = trainer.predict(val_ds).predictions
decoded_preds = processor.tokenizer.batch_decode(preds, skip_special_tokens=True)
references = val_df[[f"caption_{i}" for i in range(1,6)]].values.tolist()

refs_dict  = {i: references[i] for i in range(len(references))}
preds_dict = {i: [decoded_preds[i]]     for i in range(len(decoded_preds))}
cider_scorer = Cider()
cider_score, _ = cider_scorer.compute_score(refs_dict, preds_dict)
print("LoRA CIDEr:", cider_score)


# Changed: Pass keyword arguments 'references' and 'predictions' to compute()
bleu_res   = evaluate.load("bleu"  ).compute(references=references, predictions=decoded_preds)["bleu"]
meteor_res = evaluate.load("meteor").compute(references=references, predictions=decoded_preds)["meteor"]
rouge_res  = evaluate.load("rouge" ).compute(references=references, predictions=decoded_preds)["rougeL"]


print(f"BLEU:    {bleu_res:.4f}")
print(f"METEOR:  {meteor_res:.4f}")
print(f"ROUGE-L: {rouge_res:.4f}")
print(f"CIDEr:   {cider_score:.4f}")

wandb.log({
    "bleu":   bleu_res,
    "meteor": meteor_res,
    "rougeL": rouge_res,
    "cider":  cider_score
})


# -------------------------------------------
# 8) Sonuçları CSV’e ve wandbye yaz
# -------------------------------------------
rows = []
for i, img_name in enumerate(val_ds.df["image"].tolist()):
    row = {"image": img_name, "pred": decoded_preds[i]}
    for j, r in enumerate(references[i], start=1):
        row[f"ref_{j}"] = r
    rows.append(row)

pd.DataFrame(rows).to_csv("lora_r8_eos_gen_val_results.csv", index=False)
print("Saved CSV → lora_r8_val_eos_gen_results.csv")

n_samples = 5
# Veri seti uzunluğu
N = len(decoded_preds)
# Rastgele indeksler
sample_idxs = random.sample(range(N), n_samples)

# Bir tablo oluştur
table = wandb.Table(columns=["image", "prediction", "references"])

for i in sample_idxs:
    img_name   = val_ds.df["image"].iloc[i]
    pred       = decoded_preds[i]
    refs       = references[i]  # list of ground-truth’ler
    # referansları tek stringde birleştir
    refs_str   = " || ".join(refs)
    table.add_data(img_name, pred, refs_str)

# Tabloyu logla
wandb.log({"examples": table})

wandb: Currently logged in as: ayca-krk (ayca-krk-metu-middle-east-technical-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.11/dist-packages/transformers/models/auto/processing_auto.py:243: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
/usr/local/lib/python3.11/dist-packages/transformers/models/auto/auto_factory.py:476: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

<ipython-input-4-b9201acbab2a>:131: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(
No label_names provided for model class `PeftModelForSeq2SeqLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainable params: 1,916,928 || all params: 2,925,383,408 || trainable%: 0.0655

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
`labels` contains `pad_token_id` which will be masked with `config.ignore_index`. You have to mask out `pad_token_id` when preparing `labels`, this behavior will be removed in v.4.46.
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(

LoRA metrics: {'eval_loss': 12.381783485412598, 'eval_runtime': 98.0121, 'eval_samples_per_second': 45.433, 'eval_steps_per_second': 5.683, 'epoch': 1.0}
LoRA CIDEr: 1.5370039261867814

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

BLEU:    0.6178
METEOR:  0.9475
ROUGE-L: 0.6449
CIDEr:   1.5370
Saved CSV → lora_r8_val_eos_gen_results.csv

In [ ]:
import os
import random
from PIL import Image
import wandb

import torch
from torch.utils.data import Dataset

from transformers import (
    AutoProcessor,
    AutoModelForImageTextToText,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    default_data_collator,
    BitsAndBytesConfig,
    GenerationConfig
)
from peft import LoraConfig, get_peft_model, TaskType
import evaluate
from pycocoevalcap.cider.cider import Cider
import pandas as pd

# -------------------------------------------
# 0) WANDB oturumunu başlat (opsiyonel)
# -------------------------------------------
wandb.init(project="DI725_FinalProject", name="lora_r8_eos_gen")

# -------------------------------------------
# 1) Processor & Base Model (8-bit + CPU offload)
# -------------------------------------------
model_name = "google/paligemma-3b-pt-224"
processor  = AutoProcessor.from_pretrained(model_name, use_auth_token=True)
tokenizer  = processor.tokenizer #eklendi

base_model = AutoModelForImageTextToText.from_pretrained(
    model_name,
    device_map="auto",
    use_auth_token=True
)

# Bellek rahatlasın diye gradient checkpointing
base_model.gradient_checkpointing_enable()
base_model.to("cuda")
base_model.eval()

# -------------------------------------------
# 2) Dinamik Caption Dataset
# -------------------------------------------
class RiscDynamicCaptionDataset(Dataset):
    def __init__(self, df, img_dir, processor, max_len=64):
        self.df      = df.reset_index(drop=True)
        self.img_dir = img_dir
        self.proc    = processor
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(os.path.join(self.img_dir, row["image"])).convert("RGB")
        caps = [row[f"caption_{i}"] for i in range(1,6)]
        cap  = "<image> " + random.choice(caps) + tokenizer.eos_token  # EOS token eklendi

        enc = self.proc(
            images=img,
            text=cap,
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors="pt"
        )
        pixel_values   = enc.pixel_values.squeeze(0)
        input_ids      = enc.input_ids.squeeze(0)
        attention_mask = enc.attention_mask.squeeze(0)

        return {
            "pixel_values":   pixel_values,
            "input_ids":      input_ids,
            "attention_mask": attention_mask,
            "labels":         input_ids.clone()
        }

# -------------------------------------------
# 3) Train / Val Dataset’leri yükle
# -------------------------------------------
img_dir  = "/content/resized"
train_ds = RiscDynamicCaptionDataset(train_df, img_dir, processor)
val_ds   = RiscDynamicCaptionDataset(val_df,   img_dir, processor)

# -------------------------------------------
# 4) LoRA Konfigürasyonu & PEFT Model
# -------------------------------------------
lora_cfg = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj"]
)
model_lora = get_peft_model(base_model, lora_cfg)
model_lora.print_trainable_parameters()

# -------------------------------------------
# 5) TrainingArguments & Trainer
# -------------------------------------------
gen_cfg = GenerationConfig(
    repetition_penalty=1.5,           # tekrarlanan token’lara 1.5× ceza
    num_beams=1,                   # greedy
    no_repeat_ngram_size=2,        # hiçbir 2-gram tekrarına izin verme
    eos_token_id=tokenizer.eos_token_id,
)

training_args = Seq2SeqTrainingArguments(
    output_dir="lora_r8",
    per_device_train_batch_size=3,
    gradient_accumulation_steps=4,
    learning_rate=5e-5,
    num_train_epochs=1,
    logging_steps=5,
    eval_strategy="epoch",
    # her `logging_steps` adımında log’la
    logging_strategy="steps",
    predict_with_generate=True,
    generation_config=gen_cfg,
    fp16=True,
    push_to_hub=False,
    report_to="wandb",
    max_steps=1500

)


trainer = Seq2SeqTrainer(
    model=model_lora,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=default_data_collator,
    tokenizer=processor
)

# -------------------------------------------
# 6) Eğitim & Değerlendirme
# -------------------------------------------
trainer.train()
lora_metrics = trainer.evaluate()
print("LoRA metrics:", lora_metrics)

# -------------------------------------------
# 7) CIDEr’i ayrı hesaplamak istersen
# -------------------------------------------
preds = trainer.predict(val_ds).predictions
decoded_preds = processor.tokenizer.batch_decode(preds, skip_special_tokens=True)
references = val_df[[f"caption_{i}" for i in range(1,6)]].values.tolist()

refs_dict  = {i: references[i] for i in range(len(references))}
preds_dict = {i: [decoded_preds[i]]     for i in range(len(decoded_preds))}
cider_scorer = Cider()
cider_score, _ = cider_scorer.compute_score(refs_dict, preds_dict)
print("LoRA CIDEr:", cider_score)


# Changed: Pass keyword arguments 'references' and 'predictions' to compute()
bleu_res   = evaluate.load("bleu"  ).compute(references=references, predictions=decoded_preds)["bleu"]
meteor_res = evaluate.load("meteor").compute(references=references, predictions=decoded_preds)["meteor"]
rouge_res  = evaluate.load("rouge" ).compute(references=references, predictions=decoded_preds)["rougeL"]


print(f"BLEU:    {bleu_res:.4f}")
print(f"METEOR:  {meteor_res:.4f}")
print(f"ROUGE-L: {rouge_res:.4f}")
print(f"CIDEr:   {cider_score:.4f}")

wandb.log({
    "bleu":   bleu_res,
    "meteor": meteor_res,
    "rougeL": rouge_res,
    "cider":  cider_score
})


# -------------------------------------------
# 8) Sonuçları CSV’e ve wandbye yaz
# -------------------------------------------
rows = []
for i, img_name in enumerate(val_ds.df["image"].tolist()):
    row = {"image": img_name, "pred": decoded_preds[i]}
    for j, r in enumerate(references[i], start=1):
        row[f"ref_{j}"] = r
    rows.append(row)

pd.DataFrame(rows).to_csv("lora_r8_eos_gen_val_results.csv", index=False)
print("Saved CSV → lora_r8_val_eos_gen_results.csv")

n_samples = 5
# Veri seti uzunluğu
N = len(decoded_preds)
# Rastgele indeksler
sample_idxs = random.sample(range(N), n_samples)

# Bir tablo oluştur
table = wandb.Table(columns=["image", "prediction", "references"])

for i in sample_idxs:
    img_name   = val_ds.df["image"].iloc[i]
    pred       = decoded_preds[i]
    refs       = references[i]  # list of ground-truth’ler
    # referansları tek stringde birleştir
    refs_str   = " || ".join(refs)
    table.add_data(img_name, pred, refs_str)

# Tabloyu logla
wandb.log({"examples": table})

wandb: Currently logged in as: ayca-krk (ayca-krk-metu-middle-east-technical-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.11/dist-packages/transformers/models/auto/processing_auto.py:243: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
/usr/local/lib/python3.11/dist-packages/transformers/models/auto/auto_factory.py:476: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

<ipython-input-5-3515243c4420>:134: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(
No label_names provided for model class `PeftModelForSeq2SeqLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainable params: 1,916,928 || all params: 2,925,383,408 || trainable%: 0.0655

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
`labels` contains `pad_token_id` which will be masked with `config.ignore_index`. You have to mask out `pad_token_id` when preparing `labels`, this behavior will be removed in v.4.46.
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(

LoRA metrics: {'eval_loss': 12.43194580078125, 'eval_runtime': 97.6634, 'eval_samples_per_second': 45.595, 'eval_steps_per_second': 5.703, 'epoch': 0.5053908355795148}
LoRA CIDEr: 0.8699742532201853

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

BLEU:    0.4783
METEOR:  0.9147
ROUGE-L: 0.8890
CIDEr:   0.8700
Saved CSV → lora_r8_val_eos_gen_results.csv

genlerden anlamıyo, acaba eğitim noktasında müdahele etmek daha mı iyi olur? pad_token:

In [ ]:
import os
import random
from PIL import Image
import wandb

import torch
from torch.utils.data import Dataset

from transformers import (
    AutoProcessor,
    AutoModelForImageTextToText,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    default_data_collator,
    BitsAndBytesConfig,
    GenerationConfig
)
from peft import LoraConfig, get_peft_model, TaskType
import evaluate
from pycocoevalcap.cider.cider import Cider
import pandas as pd
from transformers import DataCollatorForSeq2Seq


# -------------------------------------------
# 0) WANDB oturumunu başlat (opsiyonel)
# -------------------------------------------
wandb.init(project="DI725_FinalProject", name="lora_r8_eos_pad")

# -------------------------------------------
# 1) Processor & Base Model (8-bit + CPU offload)
# -------------------------------------------
model_name = "google/paligemma-3b-pt-224"
processor  = AutoProcessor.from_pretrained(model_name, use_auth_token=True)
tokenizer  = processor.tokenizer #eklendi

base_model = AutoModelForImageTextToText.from_pretrained(
    model_name,
    device_map="auto",
    use_auth_token=True
)

# Bellek rahatlasın diye gradient checkpointing
base_model.gradient_checkpointing_enable()
base_model.to("cuda")
base_model.eval()

# -------------------------------------------
# 2) Dinamik Caption Dataset
# -------------------------------------------
class RiscDynamicCaptionDataset(Dataset):
    def __init__(self, df, img_dir, processor, max_len=64):
        self.df      = df.reset_index(drop=True)
        self.img_dir = img_dir
        self.proc    = processor
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(os.path.join(self.img_dir, row["image"])).convert("RGB")
        caps = [row[f"caption_{i}"] for i in range(1,6)]
        cap  = "<image> " + random.choice(caps) + tokenizer.eos_token  # EOS token eklendi

        enc = self.proc(
            images=img,
            text=cap,
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors="pt"
        )
        pixel_values   = enc.pixel_values.squeeze(0)
        input_ids      = enc.input_ids.squeeze(0)
        attention_mask = enc.attention_mask.squeeze(0)

        return {
            "pixel_values":   pixel_values,
            "input_ids":      input_ids,
            "attention_mask": attention_mask,
            "labels":         input_ids.clone()
        }

# -------------------------------------------
# 3) Train / Val Dataset’leri yükle
# -------------------------------------------
img_dir  = "/content/resized"
train_ds = RiscDynamicCaptionDataset(train_df, img_dir, processor)
val_ds   = RiscDynamicCaptionDataset(val_df,   img_dir, processor)

# -------------------------------------------
# 4) LoRA Konfigürasyonu & PEFT Model
# -------------------------------------------
lora_cfg = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj"]
)
model_lora = get_peft_model(base_model, lora_cfg)
model_lora.print_trainable_parameters()

# -------------------------------------------
# 5) TrainingArguments & Trainer
# -------------------------------------------

training_args = Seq2SeqTrainingArguments(
    output_dir="lora_r8",
    per_device_train_batch_size=3,
    gradient_accumulation_steps=4,
    learning_rate=5e-5,
    num_train_epochs=1,
    logging_steps=5,
    eval_strategy="epoch",
    # her `logging_steps` adımında log’la
    logging_strategy="steps",
    predict_with_generate=True,
    fp16=True,
    push_to_hub=False,
    report_to="wandb",
    max_steps=1500

)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=processor.tokenizer,
    label_pad_token_id=-100
)

trainer = Seq2SeqTrainer(
    model=model_lora,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=data_collator,
    tokenizer=processor
)

# -------------------------------------------
# 6) Eğitim & Değerlendirme
# -------------------------------------------
trainer.train()
lora_metrics = trainer.evaluate()
print("LoRA metrics:", lora_metrics)

# -------------------------------------------
# 7) CIDEr’i ayrı hesaplamak istersen
# -------------------------------------------
preds = trainer.predict(val_ds).predictions
decoded_preds = processor.tokenizer.batch_decode(preds, skip_special_tokens=True)
references = val_df[[f"caption_{i}" for i in range(1,6)]].values.tolist()

refs_dict  = {i: references[i] for i in range(len(references))}
preds_dict = {i: [decoded_preds[i]]     for i in range(len(decoded_preds))}
cider_scorer = Cider()
cider_score, _ = cider_scorer.compute_score(refs_dict, preds_dict)
print("LoRA CIDEr:", cider_score)


# Changed: Pass keyword arguments 'references' and 'predictions' to compute()
bleu_res   = evaluate.load("bleu"  ).compute(references=references, predictions=decoded_preds)["bleu"]
meteor_res = evaluate.load("meteor").compute(references=references, predictions=decoded_preds)["meteor"]
rouge_res  = evaluate.load("rouge" ).compute(references=references, predictions=decoded_preds)["rougeL"]


print(f"BLEU:    {bleu_res:.4f}")
print(f"METEOR:  {meteor_res:.4f}")
print(f"ROUGE-L: {rouge_res:.4f}")
print(f"CIDEr:   {cider_score:.4f}")

wandb.log({
    "bleu":   bleu_res,
    "meteor": meteor_res,
    "rougeL": rouge_res,
    "cider":  cider_score
})


# -------------------------------------------
# 8) Sonuçları CSV’e ve wandbye yaz
# -------------------------------------------
rows = []
for i, img_name in enumerate(val_ds.df["image"].tolist()):
    row = {"image": img_name, "pred": decoded_preds[i]}
    for j, r in enumerate(references[i], start=1):
        row[f"ref_{j}"] = r
    rows.append(row)

pd.DataFrame(rows).to_csv("lora_r8_eos_pad_val_results.csv", index=False)
print("Saved CSV → lora_r8_val_eos_pad_results.csv")

n_samples = 5
# Veri seti uzunluğu
N = len(decoded_preds)
# Rastgele indeksler
sample_idxs = random.sample(range(N), n_samples)

# Bir tablo oluştur
table = wandb.Table(columns=["image", "prediction", "references"])

for i in sample_idxs:
    img_name   = val_ds.df["image"].iloc[i]
    pred       = decoded_preds[i]
    refs       = references[i]  # list of ground-truth’ler
    # referansları tek stringde birleştir
    refs_str   = " || ".join(refs)
    table.add_data(img_name, pred, refs_str)

# Tabloyu logla
wandb.log({"examples": table})

wandb: Currently logged in as: ayca-krk (ayca-krk-metu-middle-east-technical-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.11/dist-packages/transformers/models/auto/processing_auto.py:243: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
/usr/local/lib/python3.11/dist-packages/transformers/models/auto/auto_factory.py:476: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

<ipython-input-4-ced1de550bd9>:133: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(
No label_names provided for model class `PeftModelForSeq2SeqLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainable params: 1,916,928 || all params: 2,925,383,408 || trainable%: 0.0655

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/usr/local/lib/python3.11/dist-packages/transformers/data/data_collator.py:741: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /pytorch/torch/csrc/utils/tensor_new.cpp:254.)
  batch["labels"] = torch.tensor(batch["labels"], dtype=torch.int64)
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
`labels` contains `pad_token_id` which will be masked with `config.ignore_index`. You have to mask out `pad_token_id` when preparing `labels`, this behavior will be removed in v.4.46.
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(

LoRA metrics: {'eval_loss': 12.436532020568848, 'eval_runtime': 226.7275, 'eval_samples_per_second': 19.64, 'eval_steps_per_second': 2.457, 'epoch': 0.5053908355795148}
LoRA CIDEr: 0.81478205666173

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

BLEU:    0.4599
METEOR:  0.8892
ROUGE-L: 0.7479
CIDEr:   0.8148
Saved CSV → lora_r8_val_eos_pad_results.csv

this didnt work either

It seems that this system does not understand from the inputs given to the config section that it should not repeat words, and this will not solve the word repeat problem. In this case, we will solve the problem not in the generation section, but in post-processing.

In [7]:
import os
import random
from PIL import Image
import wandb

import torch
from torch.utils.data import Dataset

from transformers import (
    AutoProcessor,
    AutoModelForImageTextToText,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    default_data_collator,
    BitsAndBytesConfig,
    GenerationConfig
)
from peft import LoraConfig, get_peft_model, TaskType
import evaluate
from pycocoevalcap.cider.cider import Cider
import pandas as pd

# -------------------------------------------
# 0) WANDB oturumunu başlat (opsiyonel)
# -------------------------------------------
wandb.init(project="DI725_FinalProject", name="lora_r8_eos_post")

# -------------------------------------------
# 1) Processor & Base Model (8-bit + CPU offload)
# -------------------------------------------
model_name = "google/paligemma-3b-pt-224"
processor  = AutoProcessor.from_pretrained(model_name, use_auth_token=True)
tokenizer  = processor.tokenizer #eklendi

base_model = AutoModelForImageTextToText.from_pretrained(
    model_name,
    device_map="auto",
    use_auth_token=True
)

# Bellek rahatlasın diye gradient checkpointing
base_model.gradient_checkpointing_enable()
base_model.to("cuda")
base_model.eval()

# -------------------------------------------
# 2) Dinamik Caption Dataset
# -------------------------------------------
class RiscDynamicCaptionDataset(Dataset):
    def __init__(self, df, img_dir, processor, max_len=64):
        self.df      = df.reset_index(drop=True)
        self.img_dir = img_dir
        self.proc    = processor
        self.max_len = max_len

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(os.path.join(self.img_dir, row["image"])).convert("RGB")
        caps = [row[f"caption_{i}"] for i in range(1,6)]
        cap  = "<image> " + random.choice(caps) + tokenizer.eos_token  # EOS token eklendi

        enc = self.proc(
            images=img,
            text=cap,
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_tensors="pt"
        )
        pixel_values   = enc.pixel_values.squeeze(0)
        input_ids      = enc.input_ids.squeeze(0)
        attention_mask = enc.attention_mask.squeeze(0)

        return {
            "pixel_values":   pixel_values,
            "input_ids":      input_ids,
            "attention_mask": attention_mask,
            "labels":         input_ids.clone()
        }

# -------------------------------------------
# 3) Train / Val Dataset’leri yükle
# -------------------------------------------
img_dir  = "/content/resized"
train_ds = RiscDynamicCaptionDataset(train_df, img_dir, processor)
val_ds   = RiscDynamicCaptionDataset(val_df,   img_dir, processor)

# -------------------------------------------
# 4) LoRA Konfigürasyonu & PEFT Model
# -------------------------------------------
lora_cfg = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj"]
)
model_lora = get_peft_model(base_model, lora_cfg)
model_lora.print_trainable_parameters()

# -------------------------------------------
# 5) TrainingArguments & Trainer
# -------------------------------------------

training_args = Seq2SeqTrainingArguments(
    output_dir="lora_r8",
    per_device_train_batch_size=3,
    gradient_accumulation_steps=4,
    learning_rate=5e-5,
    num_train_epochs=1,
    logging_steps=5,
    eval_strategy="epoch",
    # her `logging_steps` adımında log’la
    logging_strategy="steps",
    predict_with_generate=True,
    fp16=True,
    push_to_hub=False,
    report_to="wandb",
    max_steps=1500

)


trainer = Seq2SeqTrainer(
    model=model_lora,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    data_collator=default_data_collator,
    tokenizer=processor
)

# -------------------------------------------
# 6) Eğitim & Değerlendirme
# -------------------------------------------
trainer.train()
lora_metrics = trainer.evaluate()
print("LoRA metrics:", lora_metrics)

raw_pred_ids = trainer.predict(val_ds).predictions  # shape: (N, seq_len)

clean_preds = []
for seq_ids in raw_pred_ids:
    # 1) İlk EOS token’ın index’ini bul
    #    (eğer eos_token_id hiç yoksa bütün seq’i kullan)
    ids = list(seq_ids)
    if tokenizer.eos_token_id in ids:
        cut = ids.index(tokenizer.eos_token_id)
        ids = ids[:cut]
    # 2) Decode & special tokens’ı at
    text = tokenizer.decode(ids, skip_special_tokens=True).strip()
    clean_preds.append(text)

# Artık clean_preds, "<pad>" ve "<image>" içermiyor,
# EOS sonrası dolguları da kesinlikle bırakmıyor.

# references
references = val_df[[f"caption_{i}" for i in range(1,6)]].values.tolist()

# CIDEr
refs_dict  = {i: references[i] for i in range(len(references))}
preds_dict = {i: [clean_preds[i]]       for i in range(len(clean_preds))}
cider_scorer = Cider()
cider_score, _ = cider_scorer.compute_score(refs_dict, preds_dict)
print("LoRA CIDEr:", cider_score)

# BLEU / METEOR / ROUGE
bleu_res   = evaluate.load("bleu" ).compute(references=references, predictions=clean_preds)["bleu"]
meteor_res = evaluate.load("meteor").compute(references=references, predictions=clean_preds)["meteor"]
rouge_res  = evaluate.load("rouge" ).compute(references=references, predictions=clean_preds)["rougeL"]

print(f"BLEU:    {bleu_res:.4f}")
print(f"METEOR:  {meteor_res:.4f}")
print(f"ROUGE-L: {rouge_res:.4f}")
print(f"CIDEr:   {cider_score:.4f}")

wandb.log({
    "bleu":   bleu_res,
    "meteor": meteor_res,
    "rougeL": rouge_res,
    "cider":  cider_score
})


# CSV ve wandb örnekleri için de clean_preds kullan
rows = []
for i, img_name in enumerate(val_ds.df["image"].tolist()):
    row = {"image": img_name, "pred": clean_preds[i]}
    for j, r in enumerate(references[i], start=1):
        row[f"ref_{j}"] = r
    rows.append(row)
pd.DataFrame(rows).to_csv("lora_r8_eos_post_val_results.csv", index=False)
print("Saved CSV → lora_r8_eos_post_val_results.csv")

table = wandb.Table(columns=["image", "prediction", "references"])
for idx in random.sample(range(len(clean_preds)), 5):
    table.add_data(val_ds.df["image"].iloc[idx],
                   clean_preds[idx],
                   " || ".join(references[idx]))
wandb.log({"examples": table})

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: ayca-krk (ayca-krk-metu-middle-east-technical-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.11/dist-packages/transformers/models/auto/processing_auto.py:243: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

preprocessor_config.json:   0%|          | 0.00/699 [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

tokenizer_config.json:   0%|          | 0.00/40.0k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.26M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/24.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/607 [00:00<?, ?B/s]

/usr/local/lib/python3.11/dist-packages/transformers/models/auto/auto_factory.py:476: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers. Please use `token` instead.
  warnings.warn(

config.json:   0%|          | 0.00/1.03k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/62.6k [00:00<?, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.95G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/1.74G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/137 [00:00<?, ?B/s]

<ipython-input-7-e19fb8fa239b>:127: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(
No label_names provided for model class `PeftModelForSeq2SeqLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainable params: 1,916,928 || all params: 2,925,383,408 || trainable%: 0.0655

wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
`labels` contains `pad_token_id` which will be masked with `config.ignore_index`. You have to mask out `pad_token_id` when preparing `labels`, this behavior will be removed in v.4.46.
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/torch/utils/checkpoint.py:87: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/transformers/models/paligemma/configuration_paligemma.py:135: FutureWarning: The `ignore_index` attribute is deprecated and will be removed in v4.47.
  warnings.warn(

LoRA metrics: {'eval_loss': 12.430432319641113, 'eval_runtime': 97.2718, 'eval_samples_per_second': 45.779, 'eval_steps_per_second': 5.726, 'epoch': 0.5053908355795148}
LoRA CIDEr: 3.1215789050485263

Downloading builder script:   0%|          | 0.00/5.94k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules:   0%|          | 0.00/3.34k [00:00<?, ?B/s]

Downloading builder script:   0%|          | 0.00/7.02k [00:00<?, ?B/s]

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

Downloading builder script:   0%|          | 0.00/6.27k [00:00<?, ?B/s]

BLEU:    1.0000
METEOR:  0.9995
ROUGE-L: 1.0000
CIDEr:   3.1216
Saved CSV → lora_r8_eos_post_val_results.csv

as it can be seen, with the post processing, the model got full score from some metrics. the words created after eos are erased

In [8]:
# 9) Gerçek skorları hesapla
import evaluate
from pycocoevalcap.cider.cider import Cider

bleu_metric   = evaluate.load("bleu")
meteor_metric = evaluate.load("meteor")
rouge_metric  = evaluate.load("rouge")
cider_scorer  = Cider()

bleu   = bleu_metric.compute(predictions=clean_preds, references=references)["bleu"]
meteor = meteor_metric.compute(predictions=clean_preds, references=references)["meteor"]
rouge  = rouge_metric.compute(predictions=clean_preds, references=references)["rougeL"]
cider, _ = cider_scorer.compute_score(
    {i: references[i]       for i in range(len(references))},
    {i: [clean_preds[i]]    for i in range(len(clean_preds))}
)

# 10) “Max possible” skorlar için perfect tahminleri hazırla
def most_common_ref(ref_list):
    sets   = [set(r.split()) for r in ref_list]
    scores = [
        sum(len(sets[i].intersection(sets[j])) for j in range(len(sets)) if j != i)
        for i in range(len(sets))
    ]
    return ref_list[scores.index(max(scores))]

perfect_preds = [most_common_ref(r) for r in references]

max_bleu   = bleu_metric.compute(predictions=perfect_preds, references=references)["bleu"]
max_meteor = meteor_metric.compute(predictions=perfect_preds, references=references)["meteor"]
max_rouge  = rouge_metric.compute(predictions=perfect_preds, references=references)["rougeL"]
max_cider, _ = cider_scorer.compute_score(
    {i: references[i]        for i in range(len(references))},
    {i: [perfect_preds[i]]   for i in range(len(perfect_preds))}
)

# 11) Skorları yazdır
print("              SCORE   /   MAX POSSIBLE")
print(f"BLEU:    {bleu:.4f} / {max_bleu:.4f}")
print(f"METEOR:  {meteor:.4f} / {max_meteor:.4f}")
print(f"ROUGE-L: {rouge:.4f} / {max_rouge:.4f}")
print(f"CIDEr:   {cider:.4f} / {max_cider:.4f}")

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

              SCORE   /   MAX POSSIBLE
BLEU:    1.0000 / 1.0000
METEOR:  0.9995 / 0.9997
ROUGE-L: 1.0000 / 1.0000
CIDEr:   3.1216 / 3.3915